name: CICD Pipeline - Par 2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: VersionControl
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Package with Maven
      run: mvn -B clean compile package --file pom.xml

    - name: Run Unit Tests
      run: mvn test

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: JsfDemoApp-war
        path: target/*.war

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t dockerponce/jsfdemoapp:${{ github.run_number }} .

    - name: Push Docker Image
      run: docker push dockerponce/jsfdemoapp:${{ github.run_number }}

    - name: Enviar notificación por correo
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: '✅ JSF Demo App - Build #${{ github.run_number }} exitoso'
        body: |
          El pipeline CI/CD para la aplicación JSF se ejecutó correctamente.
          Imagen Docker generada: dockerponce/jsfdemoapp:${{ github.run_number }}
          Repositorio: ${{ github.repository }}
          Commit: ${{ github.sha }}
        to: mauricioponceguzman@gmail.com
        from: GitHub Actions <${{ secrets.EMAIL_USERNAME }}>
        secure: true
